######################################################################
# Automatically generated by qmake (2.01a) Tue Jan 20 13:57:46 2009
######################################################################

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets
TEMPLATE = app
TARGET =testTr
DEPENDPATH += .
INCLUDEPATH += .
TRANSLATIONS=Language_Chn.ts
TRANSLATIONS=Language_Eng.ts

# Input
HEADERS += testTrDlg.h
FORMS += testTrDlg.ui
SOURCES += main.cpp testTrDlg.cpp
